### ISSUE TITLE
[BUG]: redirecting to `/auth/login` automatically when we click on the back button 

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/RepoRater#66] opened 2024-01-01 02:54 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

Redirecting to `/auth/login` automatically when we click on the back button.   

### Steps to Reproduce

To produce the error please go - 
- to the production site
- click on the `Add rating`, it will redirect to the `/auth/login` 
- now click on the back icon & you will face the error. 

I have added the recording please check  

### Screenshots

https://github.com/EddieHubCommunity/RepoRater/assets/88102392/cab4dfb6-1ad3-493e-bb67-f64f0e398de8

### Do you want to work on this issue?

No

**Comment by adityaoberai** [comment] 2024-01-03 11:53
This seems to be expected behaviour to prevent a user from adding a rating without logging in. @eddiejaoude can probably clarify more here but I think makes sense to auto-redirect to the login page before the rating is added.

**Comment by eddiejaoude** [comment] 2024-01-03 12:01
Thank you for raising the issue. Yes @adityaoberai  is correct, this page is protected as only authenticated users can give a rating 👍 

@priyankarpal if you log in with your GitHub (single click), this won't happen and you can rate as many repos as you like.

So I will close this issue.

**Closed by eddiejaoude** 2024-01-03 12:01 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix

**Comment by priyankarpal** [comment] 2024-01-03 12:05
> Thank you for raising the issue. Yes @adityaoberai is correct, this page is protected as only authenticated users can give a rating 👍
> 
> @priyankarpal if you log in with your GitHub (single click), this won't happen and you can rate as many repos as you like.
> 
> So I will close this issue.

got it
