### ISSUE TITLE
Logo/Name in nav navigate to home page

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/RepoRater#29] opened 2023-12-23 12:34 UTC
### Description

Per Divyanish’s comment in the livestream, the GitHub Repo logo doesn’t direct users to the list page

**Comment by eddiejaoude** [comment] 2023-12-23 12:37
Duplicate of https://github.com/EddieHubCommunity/RepoRater/issues/27

**Closed by eddiejaoude** 2023-12-23 12:37 UTC
Labels: bug
